# Generated by Django 2.2.20 on 2021-04-18 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0002_auto_20210408_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIDReference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tin', models.CharField(max_length=11)),
            ],
        ),
    ]
