# Generated by Django 2.2.19 on 2021-04-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlistingBusiness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlistbusiness',
            name='contactDetails',
        ),
        migrations.RemoveField(
            model_name='enlistbusiness',
            name='location',
        ),
    ]
