# Generated by Django 2.2.19 on 2021-04-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlistingBusiness', '0002_auto_20210405_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlistbusiness',
            old_name='avgPrices',
            new_name='averagePrice',
        ),
    ]
